### PR TITLE
fix socket close bug

### PR DESCRIPTION
**Pull request by plukevdh**
stolen from other branch changes

### CODE REVIEW

**Comment by fromonesrc** [comment]
@plukevdh @tecnobrat @cdwills @pklingem is this something we want to merged? I haven't heard anything about this in months so may not be something we care about now 🤷‍♂️

**Comment by plukevdh** [comment]
this was a good fix™ but if it seems solid otherwise then 🤷‍♂️

**Comment by cdwills** [comment]
i have absolutely no idea. :-) 
But you can add me to your newsletter to learn more :-D

**Comment by plukevdh** [comment]
"Luke van der Hoeven would like to add you to his LinkedIn network"

**Comment by tecnobrat** [comment]
I do not believe this is useful for us at all.  We use rsyslog from docker, and thats a better solution for us.  I don't think we'd ever log like this. So I'm gonna close this.

**Pull request closed without merging**
